# Generated by Django 5.0.7 on 2024-07-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
