# Generated by Django 5.0.7 on 2024-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('Recommended', 'Recommended'), ('Show Live', 'Show Live'), ('All movies', 'All movies')], max_length=20),
        ),
    ]
