# Generated by Django 5.0.7 on 2024-07-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_media_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
