# Generated by Django 5.0.7 on 2024-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_media_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
